# -*- coding: utf-8 -*-
"""regina-council-week-2-project-sqlcc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/counciliregina/9aea42e732318a5c8149c5eaad388573/regina-council-week-2-project-sqlcc.ipynb

> 1. DUPLICATE THIS COLAB TO START WORKING ON IT. Using File > Save a copy to drive.
> 2. SHARE SETTINGS: In the new notebook, set the sharing settings to "Anyone with the link" can be a "Commenter" by clicking "Share" on the top right corner.

<center>
<img src=https://live-production.wcms.abc-cdn.net.au/4d72b144a5661c8423472b84e0b11720 width="400"></center><br />


# Week 2: Summarize data of Airbnb Sydney!

Welcome to the project for week 2 of our *SQL Crash Course*! To earn your certificate in this class, you must submit both assignments. If you need any help, post in the questions channel on Slack or attend Office Hours. We're here to help you!

This week, we went over ways to aggregate your data and learned other intricacies of SQL. We will implement these concepts in this week's project, but as you know, with a slight twist. You are still the General Manager at Airbnb Sydney, and you'll again encounter some scenarios that you'll solve by using SQL!

## Prerequisite configuration
Below we install the software required to run this project. Please make sure to **RUN IT** by clicking on the play-button icon when you hover on the empty square bracket. And feel free to ignore the content of these two hidden cells.

IMPORTANT: These cells may have to be rerun every time you are away from the notebook a long time or access notebook on a different browser or a different laptop. If you see an error that says "NameError: name 'run' is not defined" you need to run these two hidden cells again.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install git+https://github.com/sb2nov/sql-cc.git

import pandas as pd
from IPython.display import display, HTML
import sqlcc
from sqlcc import check

# Show all the rows (instead of only a few)
pd.set_option("display.max_rows", None)

# Set precision to max 2 decimals
pd.set_option('precision', 2)

# Set CSS Style for Table
# Make it work with night & light mode
# - Alternating rows
# - th elements
# - td elements
css_style = '''
<style>
  html {
    --td-font-color: black;
    --font-color: black;
    --background-color: #e0e0e0;
  }
  html[theme=dark] {
    --td-font-color: white;
    --font-color: black;
    --background-color: #6688ff;
  }
  th {
    background: #fbd44c;
    color: var(--font-color);
    font-size: 16px;
    text-align: center;
    font-weight: bold;
  }
  tr:nth-child(even) {
    background-color: var(--background-color);
    color: var(--font-color);
  }
  td {
    font-size: 14px;
    color: var(--td-font-color);
  }
</style>
'''


def run(sql_query):
  df = sqlcc.run(sql_query)
  
  # Puts the scrollbar next to the DataFrame
  display(HTML(css_style + 
               "<div style='max-height: 500px; overflow: auto; width: fit-content; border-style: solid;" + 
               " border-width: 1px; border-color: #0139fe; font-family: GT Planar,Inter,Arial,sans-serif;'>" +
               df.style.render() +
               "</div>"))

"""## Introduction

As the General Manager for the Sydney area at Airbnb, you want to know more about the different listings of houses you onboarded. You have access to information regarding the **listings**, **neighbourhoods**, **reviews**, and **calendar**. Each of these have their own separate table, and follow the structure as shown in the week 1 project:

<img src="https://corise.com/static/course/sql-crash-course/assets/cl9owz44x005e13a00fb5fhl0/Screen Shot 2022-10-25 at 5.42.23 PM.png" height="450">

## Running and Testing Queries (Gentle reminder!)

To access the data contained in these four previously mentioned tables, you'll need to write SQL between the triple quotation marks, like:

```
query = '''
SELECT * FROM neighbourhoods
'''
run(query)
check(q2_1_1 = query)
```

Then that SQL is pulled through a `run()`-command and a `check()`-command so  you can see the output of the SQL query and whether you wrote the expected query. You can see this after the output. If you've done it correctly, you'll see **"Your SQL query is correct!"**.
"""

### Question: q2_1_1
query = "SELECT * FROM neighbourhoods"

run(query)
check(q2_1_1 = query)

"""
This vertically-scrollable table displays all of the data contained in the listings table. Feel free to explore all four tables again to familiarize yourself with the data.

## Aggregation adventures

As General manager for Airbnb Sydney, you need to make data-driven decisions about your region. You've already had many encounters with hosts calling in, and you anticipate many more scenarios that will require you to use SQL in the future. Let's work through some of these scenarios.

---

## Part 1: Printing a list of hosts whose names start with the letters Jos...

Rosa is a stellar support person who works on your team at Airbnb Sydney. She is often the first person who people speak with when they call the Airbnb Sydney office. Rosa recently got a call from a host who had experienced some issues, which she was able to successfully resolve. It's now a week later, and she would like to follow-up with the host to see if they have encountered any additional problems. Unfortunately, Rosa didn't write down the *host_id* and only remembers that the host's name started with "Jos". Upset, Rosa asks if you can write a query that matches this description?"""

### Question: q2_2_1
# Instructions: 
# 1/ Fetch all columns from the listings table
# 2/ Make sure you filtered the data to names that start with Jos

# TO BE COMPLETED
query = """
SELECT * 
FROM listings 
WHERE host LIKE 'Jos_%';
"""

run(query)
check(q2_2_1 = query)

"""Before Rosa follows up with the host, she wants to make sure that she is prepared for the call. Please write a SQL query that will give Rosa the following info information about the host:
- the neighbourhood name
- the availability of the room on the calendar
- if there are any reviews written for the room

After running these queries, please write a short summary of your findings.
"""

### Question: q2_2_2a
# Instructions: 
# 1/ Fetch all columns from the neighbourhoods table
# 2/ Make sure you filtered the data on the 
# neighbourhood id of the host name starting with Jos...

# TO BE COMPLETED
query = """
SELECT * 
FROM neighbourhoods 
WHERE neighbourhood_id = '21';
"""

run(query)
check(q2_2_2a = query)

### Question: q2_2_2b
# Instructions: 
# 1/ Fetch all columns from the calendar table
# 2/ Make sure you filtered the data on the 
# listing id of the host name starting with Jos...

# TO BE COMPLETED
query = """
SELECT * 
FROM calendar 
WHERE listing_id = '22296011';
"""

run(query)
check(q2_2_2b = query)

### Question: q2_2_2c
# Instructions: 
# 1/ Fetch all columns from the reviews table
# 2/ Make sure you filtered the data on the 
# listing id of the host name starting with Jos...

# TO BE COMPLETED
query = """
SELECT * 
FROM reviews 
WHERE listing_id = '22296011';
"""

run(query)
check(q2_2_2c = query)

"""If you've made it this far, you've found that the host's name is "Joshua." He lives in Marrickville, has no availablility all week, and no reviews have been made for his room.

If you're stuck, just post in our questions channel on Slack!

---

## Part 2: Airbnb Melbourne called...

Airbnb Melbourne has been in operation longer than our office in Sydney. They called to gauge the prices that we have for our listings. They wanted to know the maximum, minimum, and average price for our listings to compare with what they're seeing in their region. Let's write these three queries!
"""

### Question: q2_3_1a
# Instructions: 
# 1/ Fetch price_in_dollar from the listings table
# 2/ Get the "Average" price across all listings

# TO BE COMPLETED
query = """
SELECT 
AVG(price_in_dollar)
FROM listings;
"""

run(query)
check(q2_3_1a = query)

### Question: q2_3_1b
# Instructions: 
# 1/ Fetch price_in_dollar from the listings table
# 2/ Get the "Maximum" price across all listings

# TO BE COMPLETED
query = """
SELECT 
MAX(price_in_dollar) 
FROM listings;
"""

run(query)
check(q2_3_1b = query)

### Question: q2_3_1c
# Instructions: 
# 1/ Fetch price_in_dollar from the listings table
# 2/ Get the "Minimum" price across all listings

# TO BE COMPLETED
query = """
SELECT 
MIN(price_in_dollar)
FROM listings;
"""

run(query)
check(q2_3_1c = query)

"""---

## Part 3: Monthly growth goals.

I've got headquarters on my back! They keep calling and asking whether we'll meet our monthly growth goals. We need to expand as quickly as possible all across Sydney. Some mentors tell me it's better to focus on places where we are already quite present. But I believe it'll serve us better to be spread out well across Sydney. I'm worried about overrepresentation in certain neighbourhoods, which might anger local officials and even put our jobs at risk.

First, let's see if we can get an overview of which neighbourhoods have the most listings. Make use of GROUP BY where we focus on neighbourhood_id and its count.
"""

### Question: q2_4_1
# Instructions:
# 1/ Fetch neighbourhood_id from the listings table and
# 2/ the number of listings in each neighbourhood -- Please count the neighbourhood_id column.

# TO BE COMPLETED
query = """
SELECT 
neighbourhood_id,
COUNT(neighbourhood_id)
FROM listings
GROUP BY neighbourhood_id;
"""

run(query)
check(q2_4_1 = query)

"""Hmm, let's make our results more a bit more useful. Order it by count descendingly. Also, which are the neighbourhoods that are least represented?"""

### Question: q2_4_2
# Instructions: 
# 1/ Fetch neighbourhood_id from the listings table
# 2/ For the second column get the number of listings in each neighbourhood
# 3/ Make sure to order by count descendingly.

# TO BE COMPLETED
query = """
SELECT 
neighbourhood_id,
COUNT(*)
FROM listings
GROUP BY neighbourhood_id
ORDER BY COUNT(*) DESC;
"""

run(query)
check(q2_4_2 = query)

"""Looks like we've 20 neighbourhoods in the listings table but quiet a few with really few listings. 

Are there neighbourhoods with no Airbnb listings?  How do we get all the neighbourhood_id's from neighbourhoods?
"""

### Question: q2_4_3b
# Instructions: 
# 1/ Fetch neighbourhood_id from the neighbourhoods table

# TO BE COMPLETED
query = """
SELECT 
neighbourhood_id
FROM neighbourhoods;
"""

run(query)
check(q2_4_3b = query)

"""We see about 38 neighbourhoods in the neighbourhoods table compared to the 20 in listings. So our analysis shows that some neighbourhoods have few listings or none at all. These might offer interesting new opportunities to explore.

---

## Part 4: Creating a new (simplified) column

Now that we've recruited hosts and have some listings, we want to improve the experience of our customers. We want to make it faster for them to go through listings that might be of interest to them. Some of our customers have a big pockets, and others don't. So we want to make three kinds of classes:
- Affordable (0 - 70 dollar per night)
- Mid-range (70 - 300 dollar per night)
- Expensive (300+ dollar per night)

Let's make a SQL case statement to create a new column called "price_range", which includes the *listing*, *listing_id*, *host*, and *host_id*.
"""

### Question: q2_6_1
# 1/ Fetch listing, listing_id, host, host_id
# from the listings table
# 2/ Create a case on price_in_dollar which takes into account:
# - Affordable < 70
# - Expensive > 300
# - Else Mid-range
# This we call price_range

# TO BE COMPLETED
query = """
SELECT 
listing,
listing_id,
host,
host_id,
CASE
WHEN price_in_dollar < 70 THEN 'Affordable'
WHEN price_in_dollar > 300 THEN 'Expensive'
ELSE 'Mid-range'
END AS price_range
FROM listings;
"""

run(query)
check(q2_6_1 = query)

"""---

## (Extra Credit) Part 5: Represented or not?

We're now interested in tracking all neighbourhoods in which we are "over-represented". Let's first count all the occurences of each neighbourhood in our `listings`-table. 
"""

### Question: q2_5_1a
# Instructions: 
# 1/ Fetch neighbourhood_id from the listings table
# 2/ For the second column get the number of listings in each neighbourhood

# TO BE COMPLETED
query = """
SELECT
neighbourhood_id,
COUNT(*)
FROM listings
GROUP BY neighbourhood_id
ORDER BY neighbourhood_id

"""

run(query)
check(q2_5_1a = query)

"""Let's limit the results to only neighbourhoods that have a count higher than 4. (TIP: GROUP BY can be extended by making use of keyword HAVING)."""

### Question: q2_5_1b
# Instructions: 
# 1/ Fetch neighbourhood_id from the listings table
# 2/ For the second column get the number of listings in each neighbourhood
# 3/ Filter this summarized count > 4 (greater than).

# TO BE COMPLETED
query = """
SELECT
neighbourhood_id,
COUNT(neighbourhood_id) 
FROM listings
GROUP BY neighbourhood_id
HAVING COUNT(neighbourhood_id) > 4



"""

run(query)
check(q2_5_1b = query)

"""---

## 🎉 CONGRATULATIONS! 

You've made it to the end of the week 2 assignment! Awesome! Next step submit the project on the CoRise platform by filling the form at the bottom here: https://corise.com/course/sql-crash-course/module/week-2-project

If you have any lingering questions, post them on Slack! As you know, we're always here to help.

And, if you want any additional challenge questions, check out the bonus extensions below.

### Bonus: Extensions
- Can you think of improving the readability of SQL queries this weeks by using [AS](https://www.w3schools.com/sql/sql_ref_as.asp)?
- Explore the data more and come up with other questions that you would like answered using SQL, now that you know more SQL concepts!
"""